# Generated by Django 5.2.4 on 2025-07-19 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('MMK', 'Kyat'), ('EUR', 'Euro')], default='USD', max_length=5),
        ),
    ]
